### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by skauss** [TagCommander/Android#16]
Hi,
we use TagCommander on Android 

    implementation 'com.tagcommander.lib:core:4.7.0'
    implementation 'com.tagcommander.lib:SDK:4.6.0'

In Crashlytics I see often this exceptions 
`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.tagcommander.lib.core.TCEventManager.callInternetUp(TCEventManager.java:169)
       at com.tagcommander.lib.core.TCNetworkReceiver.sendInternetUpNotification(TCNetworkReceiver.java:200)
       at com.tagcommander.lib.core.TCNetworkReceiver.treatConnectivity(TCNetworkReceiver.java:249)
       at com.tagcommander.lib.core.TCNetworkReceiver$1.onAvailable(TCNetworkReceiver.java:138)
       at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3363)
       at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3581)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.os.HandlerThread.run(HandlerThread.java:67)`

Most on Android 10 and 12 on Samsung and Huawei devices.

Regards
Stephan

**Comment by CommandersAct** [comment]
Hello !
Acknowledged. I'll make a fix asap.

**Comment by CommandersAct** [comment]
Should be fixed with TCCore 4.7.1!
