### ISSUE TITLE
TCPrivacy crash

### ISSUE THREAD

**Issue by tao1** [TagCommander/Android#17]
```
Fatal Exception: java.lang.NoSuchMethodError: No static method saveMapToSharedPreferences(Ljava/util/HashMap;Landroid/content/Context;Z)V in class Lq5/l; or its super classes (declaration of 'q5.l' appears in base.apk)
       at com.tagcommander.lib.privacy.TCPrivacy.saveInSharedPreferences(TCPrivacy.java:713)
       at com.tagcommander.lib.privacy.TCPrivacy.propagateConsent(TCPrivacy.java:427)
       at com.tagcommander.lib.privacy.TCPrivacy.saveConsentWithTypeAction(TCPrivacy.java:460)
       at com.tagcommander.lib.privacy.TCPrivacy.saveConsentFromConsentSourceWithPrivacyAction(TCPrivacy.java:544)
       at com.tagcommander.lib.privacy.TCPrivacy.saveConsentFromPopUp(TCPrivacy.java:503)
       at <hidden app for this stacktrace>
       at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

Here are my app dependencies:
```
    implementation 'com.tagcommander.lib:core:4.7.1'
    implementation 'com.tagcommander.lib:SDK:4.6.0'
    implementation 'com.tagcommander.lib:privacy:4.10.4'
```

**Comment by CommandersAct** [comment]
Hello ! 
Indeed the function that it's trying to access is only in core 4.7.3 we forgot to put a warning inside the changelogs and it seems like you updated the 2 other modules but not the core one.

**Comment by tao1** [comment]
Indeed, core version 5.0.0 literally hides this update.
