### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by rlentieul** [TagCommander/Android#5]
Hello,

I recently add the TagCommander Library in my android app and I am facing an awkward exception : 
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.tagcommander.lib.core.TCDynamicStore.addData(SourceFile:43)
       at com.tagcommander.lib.TCPredefinedVariables.addData(SourceFile:1114)
       at com.tagcommander.lib.TCPredefinedVariables.onReceive(SourceFile:1448)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(SourceFile:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(SourceFile:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(SourceFile:116)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5650)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

I am using the 4.1.6 version of the Core lib, the 4.1.4 of the SDK lib and 4.1.1 if the Segment lib.

**Comment by CommandersAct** [comment]
Hello !
It seems that we have some synchronisation issues. I though I corrected everything in the 4.1.4 :(

Edit: Can you test with the SDK 4.1.5? If I remember correctly I added one more concurrency check in this version.

I'll take a look this sprint, thank you for reporting.

**Comment by rlentieul** [comment]
Hello ! 
Unfortunately, I do not reproduce this issue, it only seems to occur with our store version.
So I can update my sdk version to 4.1.5 but I can not say if this will correct the problem.

Can it be ensured that it will not occur with SDK 4.1.5 ?

Thanks for your support.

**Comment by CommandersAct** [comment]
Sadly I can't be sure of it.

**Comment by rlentieul** [comment]
Ok,
I will try with the last sdk version then.
I will let you know if this still occurs with the next release.

Thank you.

**Comment by CommandersAct** [comment]
Hello @rlentieul,
Have you been able to put a new release in production and test with the latest version of the SDK?

Thank you!

**Comment by rlentieul** [comment]
Hello,
I put a new release with the latest version of the SDK. 
Unfortunately, I still have the same issue.

**Comment by CommandersAct** [comment]
I'll start looking more into it starting the next sprint (Monday).
Is it still the same stacktrace?

**Comment by rlentieul** [comment]
Yes it is the same stacktrace.

**Comment by rlentieul** [comment]
Hi,
Do you have any updates about this issue ?

**Comment by CommandersAct** [comment]
Hello, not yet sorry, I didn't had much time :(

**Comment by rlentieul** [comment]
Hello,
I am still facing this issue.
Do you have any updates about it?

**Comment by CommandersAct** [comment]
Sadly, still low on time for that, we're running with GDPR :(

**Comment by CommandersAct** [comment]
Hello !
I changed the way I treat the Map and the synchronisation for the List, I've created a beta that you can test here:

https://github.com/TagCommander/Android/tree/master/Beta

Sorry for the long wait :(
